name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

jobs:
  test: # give our job an ID
    runs-on: ubuntu-latest # the image our job will run on
    name: Test affected # the name that will appear on the Actions UI
    steps: # what steps it will perform
      - uses: actions/checkout@v1 # checkout whatever branch the PR is using
      - uses: bahmutov/npm-install@v1.4.5 # trigger an `npm install`
      - run: npm run nx affected -- --target=test --base=origin/main --parallel
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=lint --base=origin/main --parallel
  e2e:
    runs-on: ubuntu-latest
    name: e2e
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=e2e --base=origin/main --parallel
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=build --base=origin/main --parallel
